# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lon_decision_extra_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dlon_decision_extra_info.proto\x12\x12lon_decision_proto\"\x1b\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\";\n\x04Pose\x12$\n\x03pos\x18\x01 \x01(\x0b\x32\x17.lon_decision_proto.Pos\x12\r\n\x05theta\x18\x02 \x01(\x01\"*\n\x07Point3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"4\n\nTrajectory\x12&\n\x04pose\x18\x01 \x03(\x0b\x32\x18.lon_decision_proto.Pose\"6\n\x07Polygon\x12+\n\x06vertex\x18\x01 \x03(\x0b\x32\x1b.lon_decision_proto.Point3d\"3\n\tLane_Node\x12&\n\x04pose\x18\x01 \x01(\x0b\x32\x18.lon_decision_proto.Pose\"G\n\x04Lane\x12+\n\x04node\x18\x01 \x03(\x0b\x32\x1d.lon_decision_proto.Lane_Node\x12\x12\n\nlane_width\x18\x02 \x01(\x01\"3\n\tLocal_Map\x12&\n\x04lane\x18\x01 \x03(\x0b\x32\x18.lon_decision_proto.Lane\"\x9e\x01\n\x0c\x45goExtraInfo\x12*\n\x08\x65go_pose\x18\x01 \x01(\x0b\x32\x18.lon_decision_proto.Pose\x12\x30\n\x0b\x65go_polygon\x18\x02 \x01(\x0b\x32\x1b.lon_decision_proto.Polygon\x12\x30\n\x08\x65go_traj\x18\x03 \x01(\x0b\x32\x1e.lon_decision_proto.Trajectory\"\xb3\x01\n\x0cObjExtraInfo\x12\x13\n\x0bobj_orig_id\x18\x01 \x01(\x05\x12*\n\x08obj_pose\x18\x02 \x01(\x0b\x32\x18.lon_decision_proto.Pose\x12\x30\n\x0bobj_polygon\x18\x03 \x01(\x0b\x32\x1b.lon_decision_proto.Polygon\x12\x30\n\x08obj_traj\x18\x04 \x01(\x0b\x32\x1e.lon_decision_proto.Trajectory\"K\n\x0fObjExtraInfoSet\x12\x38\n\x0eobj_extra_info\x18\x01 \x03(\x0b\x32 .lon_decision_proto.ObjExtraInfo\"\xc3\x01\n\x14LonDecisionExtraInfo\x12\x38\n\x0e\x65go_extra_info\x18\x01 \x01(\x0b\x32 .lon_decision_proto.EgoExtraInfo\x12\x30\n\tlocal_map\x18\x02 \x01(\x0b\x32\x1d.lon_decision_proto.Local_Map\x12?\n\x12obj_extra_info_set\x18\x03 \x01(\x0b\x32#.lon_decision_proto.ObjExtraInfoSetb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lon_decision_extra_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POS._serialized_start=53
  _POS._serialized_end=80
  _POSE._serialized_start=82
  _POSE._serialized_end=141
  _POINT3D._serialized_start=143
  _POINT3D._serialized_end=185
  _TRAJECTORY._serialized_start=187
  _TRAJECTORY._serialized_end=239
  _POLYGON._serialized_start=241
  _POLYGON._serialized_end=295
  _LANE_NODE._serialized_start=297
  _LANE_NODE._serialized_end=348
  _LANE._serialized_start=350
  _LANE._serialized_end=421
  _LOCAL_MAP._serialized_start=423
  _LOCAL_MAP._serialized_end=474
  _EGOEXTRAINFO._serialized_start=477
  _EGOEXTRAINFO._serialized_end=635
  _OBJEXTRAINFO._serialized_start=638
  _OBJEXTRAINFO._serialized_end=817
  _OBJEXTRAINFOSET._serialized_start=819
  _OBJEXTRAINFOSET._serialized_end=894
  _LONDECISIONEXTRAINFO._serialized_start=897
  _LONDECISIONEXTRAINFO._serialized_end=1092
# @@protoc_insertion_point(module_scope)
