# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lon_decision_output.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lon_decision_result_pb2 as lon__decision__result__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19lon_decision_output.proto\x12\x12lon_decision_proto\x1a\x19lon_decision_result.proto\"j\n\x11LonDecisionOutput\x12\x11\n\tframe_idx\x18\x01 \x01(\x05\x12\x42\n\x13lon_decision_result\x18\x02 \x01(\x0b\x32%.lon_decision_proto.LonDecisionResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lon_decision_output_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LONDECISIONOUTPUT._serialized_start=76
  _LONDECISIONOUTPUT._serialized_end=182
# @@protoc_insertion_point(module_scope)
