# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lon_decision_input.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lon_decision_ego_info_pb2 as lon__decision__ego__info__pb2
from . import lon_decision_obj_info_pb2 as lon__decision__obj__info__pb2
from . import lon_decision_result_pb2 as lon__decision__result__pb2
from . import lon_decision_extra_info_pb2 as lon__decision__extra__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18lon_decision_input.proto\x12\x12lon_decision_proto\x1a\x1blon_decision_ego_info.proto\x1a\x1blon_decision_obj_info.proto\x1a\x19lon_decision_result.proto\x1a\x1dlon_decision_extra_info.proto\"\xf0\x01\n\x10LonDecisionInput\x12-\n\x08\x65go_info\x18\x01 \x01(\x0b\x32\x1b.lon_decision_proto.EgoInfo\x12+\n\x07obj_set\x18\x02 \x01(\x0b\x32\x1a.lon_decision_proto.ObjSet\x12\x42\n\x13lon_decision_result\x18\x03 \x01(\x0b\x32%.lon_decision_proto.LonDecisionResult\x12<\n\nextra_info\x18\x04 \x01(\x0b\x32(.lon_decision_proto.LonDecisionExtraInfob\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lon_decision_input_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LONDECISIONINPUT._serialized_start=165
  _LONDECISIONINPUT._serialized_end=405
# @@protoc_insertion_point(module_scope)
