# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lon_decision_ego_info.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1blon_decision_ego_info.proto\x12\x12lon_decision_proto\"I\n\x07\x45goInfo\x12\x0b\n\x03vel\x18\x01 \x01(\x02\x12\x0f\n\x07min_acc\x18\x02 \x01(\x02\x12\x0f\n\x07max_acc\x18\x03 \x01(\x02\x12\x0f\n\x07max_vel\x18\x04 \x01(\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lon_decision_ego_info_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EGOINFO._serialized_start=51
  _EGOINFO._serialized_end=124
# @@protoc_insertion_point(module_scope)
